version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0

jobs:
  scan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: robinyms101/flask-docker-app-for-devops
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME

workflows:
  scan:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build
          filters:
            branches:
              only: main
      # The scan job
      - scan:
          requires:
            - build
          filters:
            branches:
              only: main