version: 2.1

orbs:
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies 
          command: pip install -r requirements.txt

  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Run Tests
          command: python -m unittest discover

  scan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: robinyms101/flask-docker-app-for-devops
    steps:
      - checkout
      - setup_remote_docker
      - docker/check:
          docker-username: DOCKERHUB_USERNAME
          docker-password: DOCKERHUB_PASSWORD
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME

  codescan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: robinyms101/flask-docker-app-for-devops
    steps:
      - checkout
      - setup_remote_docker
      - docker/check:
          docker-username: DOCKERHUB_USERNAME
          docker-password: DOCKERHUB_PASSWORD
      - run: docker build -t $IMAGE_NAME .
      - snyk/code:
          command: "snyk code test"

workflows:
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build
          filters:
            branches:
              only: main
      # The scan job
      - scan:
          requires:
            - build
          filters:
            branches:
              only: main
      - codescan:
          requires:
            - build
          filters:
            branches:
              only: main