version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable # CircleCI base image with Docker
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.24   # Enables Docker commands in CircleCI

      - run:
          name: Build Docker Image
          command: docker build -t robinyms101/flask-docker-app-for-devops:latest .

  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - setup_remote_docker
      
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Push Docker Image
          command: |
            echo "Push Docker image..."
            docker push robinyms101/flask-docker-app-for-devops:latest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - publish:
          requires:
            - build

  		ALWAYS make sure to use the json schema in instructions to respond.