version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Run Tests
          command: python -m unittest discover

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build